"""Initial molecules table
Revision ID: 530a29bf0de6
Revises: None
Create Date: 2025-11-10 13:51:11.001583
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "530a29bf0de6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "molecules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("smiles_string", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_molecules_id"), "molecules", ["id"], unique=False)
    op.create_index(op.f("ix_molecules_name"), "molecules", ["name"], unique=False)
    op.create_index(
        op.f("ix_molecules_smiles_string"), "molecules", ["smiles_string"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_molecules_smiles_string"), table_name="molecules")
    op.drop_index(op.f("ix_molecules_name"), table_name="molecules")
    op.drop_index(op.f("ix_molecules_id"), table_name="molecules")
    op.drop_table("molecules")
    # ### end Alembic commands ###
